### ISSUE TITLE
jvm-reactors always has Never run status

### ISSUE THREAD

**Issue by haisum** [redskyops/redskyops-recipes#13]
I am trying to run jvm-reactors recipe on my test cluster and it always stays in 'Never run' status. 

Here's kustomize command I am executing:

`kustomize build github.com/redskyops/redskyops-recipes/jvm | \
  kubectl apply -f -`

Postgres recipe did run on this cluster succesfully and gave results in the end.

Does jvm-reactors recipe need some sort of Job to be defined?

**Comment by bradbeam** [comment]
Not seeing any issues when running locally. 

```sh
bradbeam@cr-2:~
[15:12:00] # kustomize build github.com/redskyops/redskyops-recipes/jvm | kubectl apply -f -
kuexperiment.redskyops.dev/jvm-reactors created
bradbeam@cr-2:~
[15:12:04] # kubectl get experiment jvm-reactors
NAME           STATUS
jvm-reactors   Running
bradbeam@cr-2:~
[15:12:10] # kubectl get job -l redskyops.dev/experiment=jvm-reactors 
NAME               COMPLETIONS   DURATION   AGE
jvm-reactors-092   0/1           22s        22s
```

Are you making any other changes to the experiment?

**Comment by haisum** [comment]
It doesn't run when using Free subscription. Apparently, we need to reduce number of trials and parameters to make it work.
